Update version numbers and po files for release
(Old svn revision: 2752)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1755,7 +1755,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=xfce4-mixer
- VERSION=3.99.1
+ VERSION=3.99.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -21402,9 +21402,9 @@ else
 fi;
 
   if test x"$ac_cv_LIBSTARTUP_NOTIFICATION_check" = x"yes"; then
-    echo "$as_me:$LINENO: checking for libstartup-notification-1.0 >= 0.4" >&5
-echo $ECHO_N "checking for libstartup-notification-1.0 >= 0.4... $ECHO_C" >&6
-    if $PKG_CONFIG --atleast-version=0.4 libstartup-notification-1.0 2> /dev/null; then
+    echo "$as_me:$LINENO: checking for libstartup-notification-1.0 >= 0.5" >&5
+echo $ECHO_N "checking for libstartup-notification-1.0 >= 0.5... $ECHO_C" >&6
+    if $PKG_CONFIG --atleast-version=0.5 libstartup-notification-1.0 2> /dev/null; then
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
@@ -21462,23 +21462,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libstartup-notification-1.0 >= 0.4" >&5
-echo $ECHO_N "checking for libstartup-notification-1.0 >= 0.4... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libstartup-notification-1.0 >= 0.5" >&5
+echo $ECHO_N "checking for libstartup-notification-1.0 >= 0.5... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libstartup-notification-1.0 >= 0.4" ; then
+        if $PKG_CONFIG --exists "libstartup-notification-1.0 >= 0.5" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking LIBSTARTUP_NOTIFICATION_CFLAGS" >&5
 echo $ECHO_N "checking LIBSTARTUP_NOTIFICATION_CFLAGS... $ECHO_C" >&6
-            LIBSTARTUP_NOTIFICATION_CFLAGS=`$PKG_CONFIG --cflags "libstartup-notification-1.0 >= 0.4"`
+            LIBSTARTUP_NOTIFICATION_CFLAGS=`$PKG_CONFIG --cflags "libstartup-notification-1.0 >= 0.5"`
             echo "$as_me:$LINENO: result: $LIBSTARTUP_NOTIFICATION_CFLAGS" >&5
 echo "${ECHO_T}$LIBSTARTUP_NOTIFICATION_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking LIBSTARTUP_NOTIFICATION_LIBS" >&5
 echo $ECHO_N "checking LIBSTARTUP_NOTIFICATION_LIBS... $ECHO_C" >&6
-            LIBSTARTUP_NOTIFICATION_LIBS=`$PKG_CONFIG --libs "libstartup-notification-1.0 >= 0.4"`
+            LIBSTARTUP_NOTIFICATION_LIBS=`$PKG_CONFIG --libs "libstartup-notification-1.0 >= 0.5"`
             echo "$as_me:$LINENO: result: $LIBSTARTUP_NOTIFICATION_LIBS" >&5
 echo "${ECHO_T}$LIBSTARTUP_NOTIFICATION_LIBS" >&6
         else
@@ -21486,7 +21486,7 @@ echo "${ECHO_T}$LIBSTARTUP_NOTIFICATION_LIBS" >&6
             LIBSTARTUP_NOTIFICATION_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            LIBSTARTUP_NOTIFICATION_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libstartup-notification-1.0 >= 0.4"`
+            LIBSTARTUP_NOTIFICATION_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libstartup-notification-1.0 >= 0.5"`
             echo $LIBSTARTUP_NOTIFICATION_PKG_ERRORS
         fi
 
@@ -21501,12 +21501,12 @@ echo "${ECHO_T}$LIBSTARTUP_NOTIFICATION_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libstartup-notification-1.0 >= 0.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libstartup-notification-1.0 >= 0.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libstartup-notification-1.0 >= 0.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libstartup-notification-1.0 >= 0.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  LIBSTARTUP_NOTIFICATION_REQUIRED_VERSION=0.4
+  LIBSTARTUP_NOTIFICATION_REQUIRED_VERSION=0.5
 
 
 
