Update configure and ChangeLog.
(Old svn revision: 3159)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22612,23 +22612,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4util-1.0 >= 4.1.99.2" >&5
-echo $ECHO_N "checking for libxfce4util-1.0 >= 4.1.99.2... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4util-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfce4util-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4util-1.0 >= 4.1.99.2" ; then
+        if $PKG_CONFIG --exists "libxfce4util-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE4_UTIL_CFLAGS" >&5
 echo $ECHO_N "checking XFCE4_UTIL_CFLAGS... $ECHO_C" >&6
-            XFCE4_UTIL_CFLAGS=`$PKG_CONFIG --cflags "libxfce4util-1.0 >= 4.1.99.2"`
+            XFCE4_UTIL_CFLAGS=`$PKG_CONFIG --cflags "libxfce4util-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_UTIL_CFLAGS" >&5
 echo "${ECHO_T}$XFCE4_UTIL_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE4_UTIL_LIBS" >&5
 echo $ECHO_N "checking XFCE4_UTIL_LIBS... $ECHO_C" >&6
-            XFCE4_UTIL_LIBS=`$PKG_CONFIG --libs "libxfce4util-1.0 >= 4.1.99.2"`
+            XFCE4_UTIL_LIBS=`$PKG_CONFIG --libs "libxfce4util-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_UTIL_LIBS" >&5
 echo "${ECHO_T}$XFCE4_UTIL_LIBS" >&6
         else
@@ -22636,7 +22636,7 @@ echo "${ECHO_T}$XFCE4_UTIL_LIBS" >&6
             XFCE4_UTIL_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE4_UTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4util-1.0 >= 4.1.99.2"`
+            XFCE4_UTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4util-1.0 >= 4.1.99"`
             echo $XFCE4_UTIL_PKG_ERRORS
         fi
 
@@ -22651,12 +22651,12 @@ echo "${ECHO_T}$XFCE4_UTIL_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4util-1.0 >= 4.1.99.2) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4util-1.0 >= 4.1.99.2) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4util-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4util-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE4_UTIL_REQUIRED_VERSION=4.1.99.2
+  XFCE4_UTIL_REQUIRED_VERSION=4.1.99
 
 
 
@@ -22714,23 +22714,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfcegui4-1.0 >= 4.1.0" >&5
-echo $ECHO_N "checking for libxfcegui4-1.0 >= 4.1.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfcegui4-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfcegui4-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfcegui4-1.0 >= 4.1.0" ; then
+        if $PKG_CONFIG --exists "libxfcegui4-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE4_GUI_CFLAGS" >&5
 echo $ECHO_N "checking XFCE4_GUI_CFLAGS... $ECHO_C" >&6
-            XFCE4_GUI_CFLAGS=`$PKG_CONFIG --cflags "libxfcegui4-1.0 >= 4.1.0"`
+            XFCE4_GUI_CFLAGS=`$PKG_CONFIG --cflags "libxfcegui4-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_GUI_CFLAGS" >&5
 echo "${ECHO_T}$XFCE4_GUI_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE4_GUI_LIBS" >&5
 echo $ECHO_N "checking XFCE4_GUI_LIBS... $ECHO_C" >&6
-            XFCE4_GUI_LIBS=`$PKG_CONFIG --libs "libxfcegui4-1.0 >= 4.1.0"`
+            XFCE4_GUI_LIBS=`$PKG_CONFIG --libs "libxfcegui4-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_GUI_LIBS" >&5
 echo "${ECHO_T}$XFCE4_GUI_LIBS" >&6
         else
@@ -22738,7 +22738,7 @@ echo "${ECHO_T}$XFCE4_GUI_LIBS" >&6
             XFCE4_GUI_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE4_GUI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfcegui4-1.0 >= 4.1.0"`
+            XFCE4_GUI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfcegui4-1.0 >= 4.1.99"`
             echo $XFCE4_GUI_PKG_ERRORS
         fi
 
@@ -22753,12 +22753,12 @@ echo "${ECHO_T}$XFCE4_GUI_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfcegui4-1.0 >= 4.1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfcegui4-1.0 >= 4.1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfcegui4-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfcegui4-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE4_GUI_REQUIRED_VERSION=4.1.0
+  XFCE4_GUI_REQUIRED_VERSION=4.1.99
 
 
 
@@ -22816,23 +22816,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for gtk+-2.0 >= 2.0.6" >&5
-echo $ECHO_N "checking for gtk+-2.0 >= 2.0.6... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for gtk+-2.0 >= 2.2.0" >&5
+echo $ECHO_N "checking for gtk+-2.0 >= 2.2.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "gtk+-2.0 >= 2.0.6" ; then
+        if $PKG_CONFIG --exists "gtk+-2.0 >= 2.2.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking GTK_CFLAGS" >&5
 echo $ECHO_N "checking GTK_CFLAGS... $ECHO_C" >&6
-            GTK_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.0.6"`
+            GTK_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.2.0"`
             echo "$as_me:$LINENO: result: $GTK_CFLAGS" >&5
 echo "${ECHO_T}$GTK_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking GTK_LIBS" >&5
 echo $ECHO_N "checking GTK_LIBS... $ECHO_C" >&6
-            GTK_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.0.6"`
+            GTK_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.2.0"`
             echo "$as_me:$LINENO: result: $GTK_LIBS" >&5
 echo "${ECHO_T}$GTK_LIBS" >&6
         else
@@ -22840,7 +22840,7 @@ echo "${ECHO_T}$GTK_LIBS" >&6
             GTK_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.0.6"`
+            GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.2.0"`
             echo $GTK_PKG_ERRORS
         fi
 
@@ -22855,12 +22855,12 @@ echo "${ECHO_T}$GTK_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (gtk+-2.0 >= 2.0.6) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (gtk+-2.0 >= 2.0.6) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (gtk+-2.0 >= 2.2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (gtk+-2.0 >= 2.2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  GTK_REQUIRED_VERSION=2.0.6
+  GTK_REQUIRED_VERSION=2.2.0
 
 
 
@@ -22918,23 +22918,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0 >= 4.0.0" >&5
-echo $ECHO_N "checking for libxfce4mcs-client-1.0 >= 4.0.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfce4mcs-client-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0 >= 4.0.0" ; then
+        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE_MCS_CLIENT_CFLAGS" >&5
 echo $ECHO_N "checking XFCE_MCS_CLIENT_CFLAGS... $ECHO_C" >&6
-            XFCE_MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0 >= 4.0.0"`
+            XFCE_MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_CLIENT_CFLAGS" >&5
 echo "${ECHO_T}$XFCE_MCS_CLIENT_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE_MCS_CLIENT_LIBS" >&5
 echo $ECHO_N "checking XFCE_MCS_CLIENT_LIBS... $ECHO_C" >&6
-            XFCE_MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0 >= 4.0.0"`
+            XFCE_MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_CLIENT_LIBS" >&5
 echo "${ECHO_T}$XFCE_MCS_CLIENT_LIBS" >&6
         else
@@ -22942,7 +22942,7 @@ echo "${ECHO_T}$XFCE_MCS_CLIENT_LIBS" >&6
             XFCE_MCS_CLIENT_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE_MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0 >= 4.0.0"`
+            XFCE_MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo $XFCE_MCS_CLIENT_PKG_ERRORS
         fi
 
@@ -22957,12 +22957,12 @@ echo "${ECHO_T}$XFCE_MCS_CLIENT_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0 >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE_MCS_CLIENT_REQUIRED_VERSION=4.0.0
+  XFCE_MCS_CLIENT_REQUIRED_VERSION=4.1.99
 
 
 
@@ -23021,23 +23021,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for xfce4-panel-1.0 >= 4.0.0" >&5
-echo $ECHO_N "checking for xfce4-panel-1.0 >= 4.0.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for xfce4-panel-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for xfce4-panel-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "xfce4-panel-1.0 >= 4.0.0" ; then
+        if $PKG_CONFIG --exists "xfce4-panel-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE4_PANEL_CFLAGS" >&5
 echo $ECHO_N "checking XFCE4_PANEL_CFLAGS... $ECHO_C" >&6
-            XFCE4_PANEL_CFLAGS=`$PKG_CONFIG --cflags "xfce4-panel-1.0 >= 4.0.0"`
+            XFCE4_PANEL_CFLAGS=`$PKG_CONFIG --cflags "xfce4-panel-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_PANEL_CFLAGS" >&5
 echo "${ECHO_T}$XFCE4_PANEL_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE4_PANEL_LIBS" >&5
 echo $ECHO_N "checking XFCE4_PANEL_LIBS... $ECHO_C" >&6
-            XFCE4_PANEL_LIBS=`$PKG_CONFIG --libs "xfce4-panel-1.0 >= 4.0.0"`
+            XFCE4_PANEL_LIBS=`$PKG_CONFIG --libs "xfce4-panel-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_PANEL_LIBS" >&5
 echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
         else
@@ -23045,7 +23045,7 @@ echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
             XFCE4_PANEL_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE4_PANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce4-panel-1.0 >= 4.0.0"`
+            XFCE4_PANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce4-panel-1.0 >= 4.1.99"`
             echo $XFCE4_PANEL_PKG_ERRORS
         fi
 
@@ -23060,12 +23060,12 @@ echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (xfce4-panel-1.0 >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (xfce4-panel-1.0 >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (xfce4-panel-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (xfce4-panel-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE4_PANEL_REQUIRED_VERSION=4.0.0
+  XFCE4_PANEL_REQUIRED_VERSION=4.1.99
 
 
 
@@ -23153,23 +23153,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for xfce-mcs-manager >= 4.0.0" >&5
-echo $ECHO_N "checking for xfce-mcs-manager >= 4.0.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for xfce-mcs-manager >= 4.1.99" >&5
+echo $ECHO_N "checking for xfce-mcs-manager >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "xfce-mcs-manager >= 4.0.0" ; then
+        if $PKG_CONFIG --exists "xfce-mcs-manager >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE_MCS_MANAGER_CFLAGS" >&5
 echo $ECHO_N "checking XFCE_MCS_MANAGER_CFLAGS... $ECHO_C" >&6
-            XFCE_MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "xfce-mcs-manager >= 4.0.0"`
+            XFCE_MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "xfce-mcs-manager >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_MANAGER_CFLAGS" >&5
 echo "${ECHO_T}$XFCE_MCS_MANAGER_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE_MCS_MANAGER_LIBS" >&5
 echo $ECHO_N "checking XFCE_MCS_MANAGER_LIBS... $ECHO_C" >&6
-            XFCE_MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "xfce-mcs-manager >= 4.0.0"`
+            XFCE_MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "xfce-mcs-manager >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_MANAGER_LIBS" >&5
 echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
         else
@@ -23177,7 +23177,7 @@ echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
             XFCE_MCS_MANAGER_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE_MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce-mcs-manager >= 4.0.0"`
+            XFCE_MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce-mcs-manager >= 4.1.99"`
             echo $XFCE_MCS_MANAGER_PKG_ERRORS
         fi
 
@@ -23192,12 +23192,12 @@ echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (xfce-mcs-manager >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (xfce-mcs-manager >= 4.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (xfce-mcs-manager >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (xfce-mcs-manager >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE_MCS_MANAGER_REQUIRED_VERSION=4.0.0
+  XFCE_MCS_MANAGER_REQUIRED_VERSION=4.1.99
 
 
 
