Modernize build system and build panel plugin as a module
Modernize configure.in.in and rename to configure.ac.in.
Require a C99 capable compiler.
Build the plugin as a module.
Remove unnecessary trickery with desktop file substitutions.
Remove HACKING, THANKS, TODO and add INSTALL file.
Fix dummy ChangeLog generation.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -31,18 +31,18 @@ AUTOMAKE_OPTIONS =							\
 	dist-bzip2
 
 distclean-local:
-	rm -rf *.spec *.cache *~
-
-rpm: dist
-	rpmbuild -ta $(PACKAGE)-$(VERSION).tar.gz
-	@rm -f $(PACKAGE)-$(VERSION).tar.gz
+	rm -rf *.cache *~ ChangeLog
 
 .PHONY: ChangeLog
 
 ChangeLog: Makefile
-	(GIT_DIR=$(top_srcdir)/.git git log > .changelog.tmp \
-	&& mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) \
-	|| (touch ChangeLog; echo 'Git directory not found: installing possibly empty changelog.' >&2)
+	$(AM_V_GEN) if GIT_DIR=$(top_srcdir)/.git git log >$@.tmp; then \
+	    mv $@.tmp $@; \
+	else \
+	    rm -f $@.tmp; \
+	    touch $@; \
+	    echo 'Could not generate ChangeLog from git: installing possibly empty changelog.' >&2; \
+	fi
 
 dist-hook: ChangeLog
 
@@ -50,12 +50,9 @@ EXTRA_DIST =								\
 	AUTHORS								\
 	ChangeLog							\
 	COPYING								\
-	HACKING								\
 	INSTALL								\
 	NEWS								\
 	README								\
-	THANKS								\
-	TODO								\
 	intltool-extract.in						\
 	intltool-merge.in						\
 	intltool-update.in
